### PR TITLE
Nie 266 suche

### PR DESCRIPTION
**Pull request by janCstoffregen**
You have to do a couple of things to do this test, I'll explain it shortly!

### CODE REVIEW

**Comment by janCstoffregen** [comment]
( after all tests pass: )

git clone --recurse-submodules https://github.com/nie-ine/nie-frontend.git
cd nie-frontend && git checkout NIE-266-suche
cd src/app/npm-package/ && git checkout NIE-suche-266 && cd ../../..

npm install
ng serve

The NIE-INE apps now include the search, if you open it and search for something, for example "der" , it should show 25 results which are highlighted. The windows are only draggable on the top, you can minimize them with the button on the top left.

**Comment by afa-unibas** [comment]
works as advertised! :sparkles:

**Comment by afa-unibas** [comment]
re-ran the integration tests yesterday, but travis cannot start Chrome within 60 seconds.

**Comment by janCstoffregen** [comment]
Ok, bitte nun um Test hier. Wenn dieser Test funktioniert, dann kann das npm modul auch gemerged werden:

https://github.com/nie-ine/npm-package/pull/8

**Comment by janCstoffregen** [comment]
ach so, ich muss noch die konflikte bereinigen

**Comment by janCstoffregen** [comment]
ok, finally, please check as described above when you have time, I the branch is ready, after successfull testing please merge nie-ine/npm-package#8 as well

**Comment by afa-unibas** [comment]
app/workflow viewer looks quite different in Chrome and Firefox, menus right in first, left in second.
The Workflow pane won't go away, once you click it: 
worflow dialog

probably just :peanuts::peanuts:

**Comment by janCstoffregen** [comment]
ok, I'll create an issue and will take care of it.

**Comment by rpriber** [comment]
Just summarizing issues @afa-unibas discovered and adding some, connected to it:

Safari and Chrome show the "NIE-INE Apps" (and the instances of the viewers) column right-aligned to the "add xy viewer" column, Firefox shows "NIE-INE Apps" and viewer instances left-aligned in the browser window, the "add xy column" right-aligned. 

If you have changed the position of a viewer window and then click on the instance of that viewer again, it loses it's position and is back to the start postion. 

Apart from those 2 little issues, the achieved progress is more than worth merging!

**Pull request merged**
