### PR TITLE
anlegen und loeschen von aktionen moegglich

### PR DESCRIPTION
**Pull request by janCstoffregen**
ToDo until done:
- [x] Each View consists of windows and their position can be saved
- [x] Actions can marked as done and are inProcess at first.
- [x] Actions in Process have a different colour than Actions that are done, and a different icon
- [x] After creating the action, you get directly to the respective working environment
- [x] Apps are visible when you go to Arbeitsflaeche
- [x] Adapt Header a little bit for the different views
- [x] Make it possible to get to the view from the action via the dropdown
- [x] Get id from URL in view
- [x] Include Action information in view
- [x] Check if action has view already
- [x] If x, y, z as input, then window should appear already
- [x] Create fake view without model to see if it works
- [x] Reproduce view
- [x] Use reconstructView to reconstruct the view
- [x] Create "Save View" Button
- [x] Get current position as output of each app.
- [x] Load view for the action
- [x] Design View - Model and Service
- [x] Bei View - Model "belongs to action" hinzufügen
- [x] Save view
- [x] ngoninit check if array of views of action has an action
- [x] Update: I have change the model of action and view. Action has now an array of view - hashes. Next: Redo Save view ( save view with hash and update Array of views in action )
- [x] When clicking save: Check if view already exists
- [x] When open and drag window, update this.view continously
- [x] Hash als Input von App, das App spielt es dann wieder zurück
- [x] Implement update function in fake backend
- [x] Generate hash for view
- [x] Clean Cache and then clean save of view
- [x] Implement get view by id from backend
- [x] Update View if it already exists
- [x] this.view does not have the hash of the existing views when it is dragged around
- [x] Dragging the window updates an "undefined" app, I have to change this and then updating the view will work.

### CODE REVIEW

**Comment by janCstoffregen** [comment]
Steps for next iteration for next branch:
- [ ] Save any kind of app, generelize model
- [ ] Delete View
-  [ ] For the first edition, the working environment is a landing page, which includes an image and a description list of views which have a description as well
- [ ] You can add a view by clicking on a plus in the edition view

**Comment by janCstoffregen** [comment]
Hi, please test the following:

1. Log in
2. Create a couple of actions, delete a couple of actions, both with the type "Gelange zur Arbeitsfläche"
3. Open one image - app, drag it to a memorable position, open nie-ine app side, scroll down, klick on save, go back to dashboard, go back to action, imageviewer should still be there.

**Comment by Padlina** [comment]
@janCstoffregen So, Dominique and I tested it and find two bugs:
1) Position
- Create new action, go to  Arbeitsfàche
- add image viewer
- reposition it
- resize it (smaller)
- save
- go dashboard
- reopen action
--> imageviewer resized to default. Position is ok

2.) doubled image viewer
- Create new action, go to  Arbeitsfàche
- add image viewer
- repositioned it
- save it
- go dashboard
- reopen action
- repositioned it
- save it
- go dashboard
- reopen action
--> now there are two image viewers: one in the original position, one in the latest position.

**Comment by janCstoffregen** [comment]
Ok, thank you for your review, I created 2 issues, I'd like to definitely include saving more than one window (obviously) but postpone saving the size of the window. 

I just wanted to merge now as well bc I had the feeling more development will start again soon for the frontend.

Would it be ok for you to merge under those circumstances @Padlina @domsteinbach

**Comment by Padlina** [comment]
@janCstoffregen But maybe, solving the second bug (the fact the windows is doubled) would be good before merging. But if you prefer to merge first, and solve this issue later, it is ok to us.

**Comment by janCstoffregen** [comment]
yes, thanks, I understand what's happening now in the first bug, I thought it happens when you want to save 2 image viewers, but it's only one, I'll fix this now, thank you for pointning this out, I did not see it before.

**Pull request merged**
